name: Build and Deploy with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker-compose build

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Test protected endpoint
        run: |
          sleep 10  # Give some time for the services to start
          response=$(curl --write-out "%{http_code}" --silent --output /dev/null http://localhost:8080/protected)
          if [ "$response" -ne 401 ]; then
            echo "Protected endpoint test failed. Expected HTTP status 401, but got $response."
            exit 1
          fi

      - name: Log out from Docker Hub
        run: docker logout

      - name: Stop Docker Compose
        if: always()
        run: docker-compose down
